### Import the processed dataset from zipped file

In [1]:
import gzip
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

with gzip.open("Preprocessed data.gz") as f:
    df = pd.read_csv(f)

df.head()

,Country Name,Country Code,Series Code,1970,1971,1972,1973,1974,1975,1976,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,AFG,DT.GPA.DPPG,2.132790e+08,2.543125e+08,2.807850e+08,3.388542e+08,4.349602e+08,5.446476e+08,6.095969e+08,...,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0
1,Afghanistan,AFG,DT.GPA.OFFT,2.132790e+08,2.543125e+08,2.807850e+08,3.388542e+08,4.349602e+08,5.446476e+08,6.095969e+08,...,0.0,0.0,0.0,29.8333,0.0,0.0,19.8356,0.0,17.9041,0.0
2,Afghanistan,AFG,DT.GPA.PRVT,2.132790e+08,2.543125e+08,2.807850e+08,3.388542e+08,4.349602e+08,5.446476e+08,6.095969e+08,...,0.0,0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0000,0.0
3,Afghanistan,AFG,DT.GRE.DPPG,2.132790e+08,2.543125e+08,2.807850e+08,3.388542e+08,4.349602e+08,5.446476e+08,6.095969e+08,...,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0
4,Afghanistan,AFG,DT.GRE.OFFT,2.132790e+08,2.543125e+08,2.807850e+08,3.388542e+08,4.349602e+08,5.446476e+08,6.095969e+08,...,0.0,0.0,0.0,81.9289,0.0,0.0,64.2646,0.0,73.0790,0.0

### Choose top 10 countries in terms of debt in 2020

In [2]:
filtered_df = df.groupby(by='Country Name').agg('sum').transpose() / 1e9

In [3]:
# https://towardsdatascience.com/creating-bar-chart-race-animation-with-python-cdb01144074e
import bar_chart_race as bcr

bcr.bar_chart_race(df = df, 
                    n_bars= 10
                    sort='desc',
                    title='Debts of top 10 countries from 1970 in Billion dollars',
                    filename = 'top_10.mp4')

C:\Users\dtngh\miniconda3\lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
C:\Users\dtngh\miniconda3\lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))